name: Publish package to the ForgeRock artifactory
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set up forgerock maven repository
        uses: actions/setup-java@v1
        with: # running setup-java and overwrites the settings.xml
          java-version: '11'
          architecture: x64
          server-id: central # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_USERNAME # env variable for username in deploy
          server-password: MAVEN_CENTRAL_TOKEN # env variable for token in deploy

      - name: Set up snapshot forgerock maven repository
        if: contains(github.ref, 'SNAPSHOT')
        uses: actions/setup-java@v1
        with: # running setup-java and overwrites the settings.xml
          java-version: '11'
          architecture: x64
          server-id: snapshots # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_USERNAME # env variable for username in deploy
          server-password: MAVEN_CENTRAL_TOKEN # env variable for token in deploy


      - name: Release package
        run:  mvn -B deploy
        env:
          MAVEN_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
